# Generated by Django 3.1.7 on 2021-03-11 09:24

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admins', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('age', models.IntegerField()),
                ('number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='nomatch', message='invalid mobile number!', regex='^[6-9]\\d{9}$')])),
                ('address', models.TextField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('IP', 'In Processing'), ('OH', 'On Hold'), ('C', 'Cancelled'), ('OFD', 'Out For Delivery'), ('R', 'Returned'), ('D', 'Delivered')], default='IP', max_length=20)),
                ('total_amount', models.IntegerField()),
                ('is_cancelled', models.BooleanField(default=False)),
                ('payment_type', models.CharField(choices=[('COD', 'COD'), ('Card', 'Card'), ('UPI', 'UPI'), ('Wallet', 'Wallet')], max_length=20)),
                ('shipping_address', models.CharField(blank=True, max_length=100)),
                ('transaction_id', models.CharField(max_length=256, unique=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='admins.items')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
